apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wego-test-app-vtkd9h06
  namespace: wego-system
resources:
- app.yaml
- wego-test-app-vtkd9h06-gitops-deploy.yaml
- wego-test-app-vtkd9h06-gitops-source.yaml
